import "./globals.css";
import Image from "next/image";
import { Space_Grotesk } from "next/font/google";
import styles from "./page.module.css";

const space_grotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={space_grotesk.className}>
        <nav className={styles.nav}>
          <a href="/">
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              className={styles.vercelLogo}
              width={100}
              height={24}
              priority
            />
          </a>
          <div>
            <a>Docs</a>
            <a>Github</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
